<template>
	<div>
		<Header></Header>
		<div class="coninter">
			<div class="help-info">
				<h2 style="margin-top:50px;">Buyer FAQ</h2>
				<h4>Q: What is isharelike.net ?</h4>
				<p>A: iShare is free gifts website for Amazon products which collects the latest deals to help buyers
					save money. Every user can choose the products they would like to buy and purchase them on Amazon at
					the lowest price.</p>
				<h4>Q:How do I get the free gift on isharelike.net ?</h4>
				<p>A: You can select free gifts products which are marked with Share Get on isharelike.net and then
					purchase the product on Amazon. After that, please submit your order details to us and we will
					refund your money.</p>
				<h4>Q:How do I get the free gift on isharelike.net ?</h4>
				<p>A: You can select products which are marked with Fee Get on isharelike.net and then purchase the
					product on Amazon. After that, please submit your order details to us and then we will refund after
					you leave 5 star review on amazon .</p>
				<h4>Q: How should I submit my order to isharelike.net?</h4>
				<p>A: After finishing your purchase on Amazon, please Bind Amazon Account or sign into your account and
					click Share Get Order on My Gifts or My Account to select the free gifts you want and then submit
					your order.</p>
				<h4>Q.Is there any difference between the ‘free get’ products and the ‘share get’ products?</h4>
				<p>A.Yes, ’free get’ products mean you need buy it from Amazon and then we will pay back later. ‘Share
					get’ products mean you need Invite enough US people to be our users and then you can get products
					which you want from Amazon.</p>
				<h4>Q:Will you cover the transaction fee charged by payment platform?</h4>
				<p>A:No, we won't. Besides, customer will incur tax and additional freight charges.</p>
				<h4>Q:I am not satisfied with the quality of the product I bought, can I return it?</h4>
				<p>A: We only recommend deals from reputable websites, and most items can be returned (unless they
					specifically state “all sales final”). If you are not satisfied with the quality of the product, you
					can contact the seller for a refund or exchange(not including the free gifts).</p>
				<h4>Q: Why are my deal requests failing?</h4>
				<p>A:1. The number of the products requests has reached the limit set by the seller.</p>
				<p>A:2. You have to finish the previous deal request in 60 minutes before you can request another one.
				</p>
				<h4>Q:Do merchants have access to my information?</h4>
				<p>A:No, currently we do not allow merchants to create account on isharelike.net . All deals submitted
					to our website are verified by our support team.</p>
				<h4>Q:How do I cancel my account?</h4>
				<p>A:We're sorry to see you go. Please contact our customer service team (support@isharelike.com) if you
					wish to cancel your account.</p>
				<h2 style="margin-top:50px;">Seller FAQ</h2>
				<h4> How do I submit my products to isharelike.net ?</h4>
				<p>A:Please provide us with the information below and we will submit your products to our website:</p>
				<ul class="text-muted">
					<li>1.Products quantities for free gifts.</li>
					<li>2.Discount details</li>
					<li>3.Amazon fulfillment channel</li>
					<li>4.Activity duration</li>
				</ul>
				<h4>Are there any restrictions on how I can offer my product?</h4>
				<p>Currently, there is no minimum or maximum on the number of products you need to offer within your
					campaigns. However, our minimum discount accepted is 20% off. Any campaigns less than this discount
					will not be approved.</p>
				<h4>How do you charge for submitting products?</h4>
				<p>We won't charge you for submitting products to our website. However, please note we will charge some
					money per order generated by isharelike.net as commission. You can contact
					us(support@isharelike.com) for more details.</p>
			</div>
		</div>
		<Footer></Footer>
	</div>
</template>

<script>
</script>

<style scoped lang="scss">
	@import '@/assets/scss/filetxt.scss';
	h4{margin-top:20px}
</style>
