 export const category=[
	{
		name:'Women’s Clothing',
		id:'1212',
		children:[
			{name:'Tops & Tees',id:'1223'},
			{name:'Hoodies & Sweatshirts',id:'1319'},
			{name:'Dresses',id:'1224'},
			{name:'Swimwear',id:'1238'},
			{name:'Blouses & Shirts',id:'1240'},
			{name:'Bottoms',id:'1247'},
			{name:'Jumpsuits',id:'1266'},
			{name:'Sleep & Lounge',id:'1264'},
			{name:'Sweaters',id:'1246'},
			{name:'Jackets & Coats',id:'1248'},
			{name:'Intimates',id:'1249'},
			{name:'Accessories',id:'1250'},
			{name:'Socks & Hosiery',id:'1265'},
			{name:'Rompers',id:'1437'},
			{name:'Bodysuits',id:'1438'},
			{name:'Suits & Sets',id:'1439'}
		]
	},
	{
		name:'Men’s Clothing',
		id:'1251',
		children:[
			{name:'Tops & Tees',id:'1252'},
			{name:'Hoodies & Sweatshirts',id:'1254'},
			{name:'Shirts',id:'1253'},
			{name:'Pants',id:'1255'},
			{name:'Suits & Blazers',id:'1256'},
			{name:'Sweaters',id:'1257'},
			{name:'Jackets & Coats',id:'1258'},
			{name:'Sleep & Lounge',id:'1259'},
			{name:'Underwear',id:'1261'},
			{name:'Accessories',id:'1262'},
			{name:'Socks',id:'1263'},
			{name:'Jeans',id:'1440'},
			{name:'Casual Shorts',id:'1442'},
			{name:'Men’s Sets',id:'1443'},
			{name:'Board Shorts',id:'1444'},
		]
	},
	{
		name:'Cellphones & Telecommunications',
		id:'1566',
		children:[
			{name:'Mobile Phones',id:'1567'},
			{name:'Phone Bags & Cases',id:'1568'},
			{name:'Power Bank',id:'1569'},
			{name:'Mobile Phone Accessories',id:'1570'},
			{name:'Mobile Phone Parts',id:'1571'},
			{name:'Communication Equipments',id:'1572'},
			{name:'Walkie Talkie',id:'1573'},
			{name:'Walkie Talkie Parts & Accessories',id:'1574'},
		]
	},
	{
		name:'Consumer Electronics',
		id:'1213',
		children:[
			{name:'Computer & Office',id:'1331'},
			{name:'Camera & Accessories',id:'1277'},
			{name:'Networking',id:'1332'},
			{name:'Smart Electronics & Office',id:'1278'},
			{name:'Earphones & Headphone',id:'1226'},
			{name:'Home Audio & Video',id:'1279'},
			{name:'VR/AR Devices',id:'1280'},
			{name:'Speakers',id:'1281'},
			{name:'Electronic Cigarettes',id:'1227'},
			{name:'Camera & Photo',id:'1550'},
			{name:'Socks',id:'1263'},
			{name:'Portable Audio & Video',id:'1501'},
			{name:'Accessories & Parts',id:'1502'},
			{name:'Video Games',id:'1504'},
			{name:'Wearable Devices',id:'1505'},
			{name:'Sports & Action Video Cameras',id:'1506'},
			{name:'360° Video Cameras & Accessories',id:'1507'},
			{name:'Home Electronic Accessories',id:'1508'},
			{name:'Robot',id:'1509'},
			{name:'HIFI Devices',id:'1510'},
			{name:'Live Equipment',id:'1511'},
			{name:'Power Source',id:'1512'}
		]
	},
	{
		name:'Office & School Supplies',
		id:'1550',
		children:[
			{name:'Pens， Pencils & Writing Supplies',id:'1551'},
			{name:'Notebooks & Writing Pads',id:'1552'},
			{name:'Labels， Indexes & Stamps',id:'1553'},
			{name:'School & Educational Supplies',id:'1554'},
			{name:'Adhesives & Tapes',id:'1555'},
			{name:'Filing Products',id:'1556'},
			{name:'Painting Supplies',id:'1557'},
			{name:'Office Binding Supplies',id:'1558'},
			{name:'Books',id:'1559'},
			{name:'Calendars， Planners & Cards',id:'1560'},
			{name:'Mail & Shipping Supplies',id:'1561'},
			{name:'Desk Accessories & Organizer',id:'1562'},
			{name:'Cutting Supplies',id:'1563'},
			{name:'Presentation Boards',id:'1564'},
			{name:'Paper',id:'1565'},
			{name:'Office Furniture',id:'1618'}
		]
	},
	{
		name:'Computer & Office',
		id:'1513',
		children:[
			{name:'Office Electronics',id:'1514'},
			{name:'Tablets',id:'1515'},
			{name:'Computer Components',id:'1516'},
			{name:'Tablet Accessories',id:'1517'},
			{name:'Computer Peripherals',id:'1518'},
			{name:'External Storage',id:'1519'},
			{name:'Memory Cards & SSD',id:'1520'},
			{name:'Cables & Connectors',id:'1521'},
			{name:'Mini PC',id:'1522'},
			{name:'Demo Board & Accessories',id:'1523'},
			{name:'Industrial Computer & Accessories',id:'1524'},
			{name:'DIY Gaming PC',id:'1525'},
			{name:'Computer Cleaners',id:'1526'},
			{name:'Laptops',id:'1527'},
			{name:'Laptop Accessories',id:'1528'},
			{name:'Gaming Laptops',id:'1529'},
			{name:'Desktops',id:'1531'},
			{name:'Servers',id:'1532'}
		]
	},
	{
		name:'Mother & Kids',
		id:'1217',
		children:[
			{name:'Girls Clothing',id:'1290'},
			{name:'Boys Clothing',id:'1291'},
			{name:'Children’s Shoes',id:'1292'},
			{name:'Feeding',id:'1295'},
			{name:'Baby Bedding',id:'1293'},
			{name:'Activity & Gear',id:'1294'},
			{name:'Pregnancy & Maternity',id:'1296'},
			{name:'Matching Family Outfits',id:'1297'},
			{name:'Baby Shoes',id:'1445'},
			{name:'Baby Care',id:'1446'},
			{name:'Safety Equipment',id:'1447'},
			{name:'Toilet Training',id:'1450'},
			{name:'Baby Souvenirs',id:'1451'},
			{name:'Baby Furniture',id:'1452'},
		]
	},
	{
		name:'Luggage & Bags',
		id:'1215',
		children:[
			{name:'Women\'s Bags',id:'1228'},
			{name:'Men’s Bags',id:'1267'},
			{name:'Kids & Baby\'s Bags',id:'1268'},
			{name:'Backpacks',id:'1229'},
			{name:'Wallets',id:'1269'},
			{name:'Coin Purses & Holders',id:'1270'},
			{name:'Luggage & Travel Bags',id:'1230'},
			{name:'Functional Bags',id:'1454'},
			{name:'Bag Parts & Accessories',id:'1455'},
		]
	},
	{
		name:'Shoes',
		id:'1219',
		children:[
			{name:'Men\'s Shoes',id:'1271'},
			{name:'Men\'s Casual Shoes',id:'1272'},
			{name:'Men\'s Boots',id:'1273'},
			{name:'Women\'s Shoes',id:'1274'},
			{name:'Women\'s Boots',id:'1275'},
			{name:'Women\'s Pumps',id:'1276'},
			{name:'Men&Women Shoes',id:'1434'},
			{name:'Women\'s Flats',id:'1456'},
			{name:'Women\'s Vulcanize Shoes',id:'1457'},
			{name:'Shoe Accessories',id:'1458'},
			{name:'Men\'s Vulcanize Shoes',id:'1459'}
		]
	},
	{
		name:'Weddings & Events',
		id:'1220',
		children:[
			{name:'Wedding Dresses',id:'1312'},
			{name:'Wedding Party Dress',id:'1313'},
			{name:'Wedding Accessories',id:'1314'},
			{name:'Bridesmaid Dresses',id:'1315'},
			{name:'Evening Dresses',id:'1316'},
			{name:'Prom Dresses',id:'1317'},
			{name:'Cocktail Dresses',id:'1318'},
			{name:'Wedding / Party Supply',id:'1584'}
		]
	},
	{
		name:'Jewelry & Watches',
		id:'1214',
		children:[
			{name:'Fine Jewelry',id:'1460'},
			{name:'Necklaces & Pendants',id:'1285'},
			{name:'Earrings',id:'1286'},
			{name:'Rings',id:'1287'},
			{name:'Bracelets & Bangles',id:'1288'},
			{name:'Brooches',id:'1320'},
			{name:'Wedding & Engagement Jewelry',id:'1461'},
			{name:'Jewelry Sets',id:'1326'},
			{name:'Beads & Jewelry Making',id:'1289'},
			{name:'Watch Accessories',id:'1325'},
			{name:'Men\'s Watches',id:'1321'},
			{name:'Women\'s Watches',id:'1322'},
			{name:'Lover\'s Watches',id:'1323'},
			{name:'Pocket & Fob Watches',id:'1324'},
			{name:'Children\'s Watches',id:'1462'},
			{name:'Women\'s Bracelet Watches',id:'1463'},
		]
	},
	{
		name:'Toys & Hobbies',
		id:'1234',
		children:[
			{name:'Remote Control Toys',id:'1298'},
			{name:'Dolls & Stuffed Toys',id:'1299'},
			{name:'Models & Building Toy',id:'1330'},
			{name:'Electronic Toys',id:'1301'},
			{name:'Diecasts & Toy Vehicles',id:'1302'},
			{name:'Baby Toys',id:'1303'},
			{name:'Classic Toys',id:'1469'},
			{name:'Learning & Education',id:'1470'},
			{name:'Outdoor Fun & Sports',id:'1471'},
			{name:'Action & Toy Figures',id:'1472'},
			{name:'Puzzles & Games',id:'1474'},
			{name:'Novelty & Gag Toys',id:'1475'},
			{name:'Stress Relief Toy',id:'1476'},
			{name:'Building & Construction Toys',id:'1477'},
			{name:'Kid\'s Party',id:'1478'},
			{name:'Hobby & Collectibles',id:'1479'},
			{name:'High Tech Toys',id:'1480'},
			{name:'Arts & Crafts， DIY toys',id:'1481'},
			{name:'Stuffed Animals & Plush',id:'1482'},
			{name:'Popular Toys',id:'1483'},
			{name:'Pretend Play',id:'1484'},
			{name:'Pools & Water Fun',id:'1485'},
		]
	},
	{
		name:'Sports & Outdoors',
		id:'1218',
		children:[
			{name:'Swimming',id:'1233'},
			{name:'Cycling',id:'1329'},
			{name:'Skiing',id:'1330'},
			{name:'Fishing',id:'1282'},
			{name:'Camping & Hiking',id:'1232'},
			{name:'Fitness & Body Building',id:'1231'},
			{name:'Roller，Skate board &Scooters',id:'1284'},
			{name:'Entertainment',id:'1283'},
			{name:'Sport Accessories',id:'1328'},
			{name:'Sports Clothing',id:'1486'},
			{name:'Sneakers',id:'1487'},
			{name:'Musical Instruments',id:'1488'},
			{name:'Hunting',id:'1489'},
			{name:'Team Sports',id:'1491'},
			{name:'Racquet Sports',id:'1492'},
			{name:'Golf',id:'1493'},
			{name:'Running',id:'1494'},
			{name:'Shooting',id:'1495'},
			{name:'Horse Racing',id:'1497'},
			{name:'Bowling',id:'1498'},
			{name:'Sports Bags',id:'1499'}
		]
	},
	{
		name:'Home & Garden',
		id:'1216',
		children:[
			{name:'Kitchen，Dining & Bar',id:'1304'},
			{name:'Home Decor',id:'1306'},
			{name:'Home Textile',id:'1307'},
			{name:'Bathroom Products',id:'1305'},
			{name:'Pet Products',id:'1308'},
			{name:'Garden Supplies',id:'1310'},
			{name:'Festive & Party Supplies',id:'1311'},
			{name:'Arts，Crafts & Sewing',id:'1464'},
			{name:'Home Storage & Organization',id:'1466'},
			{name:'Household Cleaning',id:'1467'},
			{name:'Household Merchandises',id:'1468'}
		]
	},
	{
		name:'Security & Protection',
		id:'1533',
		children:[
			{name:'Video Surveillance',id:'1534'},
			{name:'Security Alarm',id:'1535'},
			{name:'Access Control',id:'1536'},
			{name:'Workplace Safety Supplies',id:'1537'},
			{name:'Door Intercom',id:'1538'},
			{name:'Self Defense Supplies',id:'1539'},
			{name:'Building Automation',id:'1540'},
			{name:'Fire Protection',id:'1541'},
			{name:'Emergency Kits',id:'1542'},
			{name:'Roadway Safety',id:'1543'},
			{name:'Safes',id:'1544'},
			{name:'Lightning Protection',id:'1545'},
			{name:'Transmission & Cables',id:'1546'},
			{name:'Security Inspection Device',id:'1547'},
			{name:'IoT Devices',id:'1548'},
			{name:'Public Broadcasting',id:'1549'}
		]
	},
	{
		name:'Beauty & Health',
		id:'1436',
		children:[
			{name:'Tools & Accessories',id:'1575'},
			{name:'Sex Products',id:'1576'},
			{name:'Health Care',id:'1577'},
			{name:'Oral Hygiene',id:'1578'},
			{name:'Nails Art & Tools',id:'1579'},
			{name:'Makeup',id:'1580'},
			{name:'Skin Care',id:'1581'},
			{name:'Shaving & Hair Removal',id:'1582'},
			{name:'Tattoos / Body Art',id:'1585'},
			{name:'Massage',id:'1586'},
			{name:'Salon / Spa Equipment',id:'1587'}
		]
	},
	{
		name:'Automobiles & Motorcycles',
		id:'1588',
		children:[
			{name:'Auto Replacement Parts',id:'1589'},
			{name:'Car Lights',id:'1590'},
			{name:'Car Electronics',id:'1591'},
			{name:'Exterior Accessories',id:'1592'},
			{name:'Motorcycle Accessories & Parts',id:'1593'},
			{name:'Interior Accessories',id:'1594'},
			{name:'Car Repair Tools',id:'1595'},
			{name:'Car Wash & Maintenance',id:'1596'},
			{name:'ATV，RV，Boat & Other Vehicle',id:'1597'},
			{name:'Travel & Roadway Product',id:'1598'}
		]
	},
	{
		name:'Tools',
		id:'1599',
		children:[
			{name:'Measurement & Analysis Instruments',id:'1600'},
			{name:'Machine Tools & Accessories',id:'1601'},
			{name:'Hand Tools',id:'1602'},
			{name:'Power Tools',id:'1603'},
			{name:'Hand & Power Tool Accessories',id:'1604'},
			{name:'Welding & Soldering Supplies',id:'1605'},
			{name:'Welding Equipment',id:'1606'},
			{name:'Woodworking Machinery & Parts',id:'1607'},
			{name:'Tool Organizers',id:'1608'},
			{name:'Garden Tools',id:'1609'},
			{name:'Tool Sets',id:'1610'},
			{name:'Abrasives',id:'1611'},
			{name:'Abrasive Tools',id:'1612'},
			{name:'Construction Tools',id:'1613'},
			{name:'Tool Parts',id:'1614'},
			{name:'Riveter Guns',id:'1615'},
			{name:'Lifting Tools & Accessories',id:'1616'},
			{name:'Industrial Supplies',id:'1617'}
		]
	}
]